-- Intentionally empty.
--
-- Local resets must not create sample balances, accounts, budgets, people, or
-- wealth records that could be mistaken for family data. New households are
-- created through public.create_household(), which adds only the real signed-in
-- person and the editable default category catalog.
